# Name of the Pipeline
name: Hello CI

# Run Name
run-name: Hello ${{ github.actor }}, this action was triggered by ${{ github.eventname }}

# When will it run
on: [push, pull_request]

# What should be done
jobs: 
  hello_job:
    # not needed otherwise the the job name, here hello_job
    name: Hello CI job
    # Runner
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, I am running on ${{ runner.os }}"
      - name: Checkout repostitory
        uses: actions/checkout@v4
      - name: List my Files
        run: |
          ls ${{ github.workspace }}
      # Setup up Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # Adding routines
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Getting started with Artifacts
      - run: echo "Hello CI" > hello.txt
      - name: Upload Artifacts
      - uses: actions/upload-artifact@v4
        with:
          # Required!
          name: hello
          path: hello.txt
          retention-days: 1
          if-no-files-found: error




